version: "3.5"

services:
  api-01: &api
    image: educhaos/rinha-2024-q1:latest
    hostname: api-01
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "265MB"

  api-02:
    <<: *api
    hostname: api-02

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-01
      - api-02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "20MB"